/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_aerserv_offheapmap_SlOhMap */

#ifndef _Included_com_aerserv_offheapmap_SlOhMap
#define _Included_com_aerserv_offheapmap_SlOhMap
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_aerserv_offheapmap_SlOhMap
 * Method:    newMap
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_aerserv_offheapmap_SlOhMap_newMap
  (JNIEnv *, jobject);

/*
 * Class:     com_aerserv_offheapmap_SlOhMap
 * Method:    put
 * Signature: (JLjava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_com_aerserv_offheapmap_SlOhMap_put
  (JNIEnv *, jobject, jlong, jstring, jlong);

/*
 * Class:     com_aerserv_offheapmap_SlOhMap
 * Method:    get
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_aerserv_offheapmap_SlOhMap_get
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_aerserv_offheapmap_SlOhMap
 * Method:    contains
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_aerserv_offheapmap_SlOhMap_contains
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_aerserv_offheapmap_SlOhMap
 * Method:    remove
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_aerserv_offheapmap_SlOhMap_remove
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_aerserv_offheapmap_SlOhMap
 * Method:    newIterator
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_aerserv_offheapmap_SlOhMap_newIterator
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_aerserv_offheapmap_SlOhMap
 * Method:    hasNext
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_aerserv_offheapmap_SlOhMap_hasNext
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_aerserv_offheapmap_SlOhMap
 * Method:    next
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_aerserv_offheapmap_SlOhMap_next
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_aerserv_offheapmap_SlOhMap
 * Method:    getKeyAtItr
 * Signature: (JJ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_aerserv_offheapmap_SlOhMap_getKeyAtItr
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_aerserv_offheapmap_SlOhMap
 * Method:    getValueAtItr
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_com_aerserv_offheapmap_SlOhMap_getValueAtItr
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_aerserv_offheapmap_SlOhMap
 * Method:    size
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_aerserv_offheapmap_SlOhMap_size
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_aerserv_offheapmap_SlOhMap
 * Method:    free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_aerserv_offheapmap_SlOhMap_free
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_aerserv_offheapmap_SlOhMap
 * Method:    freeItr
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_aerserv_offheapmap_SlOhMap_freeItr
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
